# Generated by Django 5.2.3 on 2025-06-13 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completed",
            name="completedDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="completed",
            name="deadLine",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="completed",
            name="scheduledDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="completed",
            name="startedDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ongoingtasks",
            name="endDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ongoingtasks",
            name="scheduledDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ongoingtasks",
            name="startedDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todotasks",
            name="endDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="todotasks",
            name="startDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
