# Generated by Django 5.2.3 on 2025-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_completed_completeddate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ongoingtasks",
            old_name="scheduledDate",
            new_name="startDate",
        ),
        migrations.AlterField(
            model_name="completed",
            name="completedDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
